name: Deploy Vite SPA to Azure App Service (Windows)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Archive dist as zip
        run: zip -r dist.zip dist

      # Login con Service Principal (requiere secret AZURE_CREDENTIALS)
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Despliegue del contenido de dist/ a App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: gestionPasantias # <-- nombre exacto del App Service
          package: dist.zip

