name: Build and deploy Vite app to Azure Web App - gestionPasantias

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and build
        run: |
          npm ci
          npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # 👉 Empaquetar SOLO el contenido de dist/ (no la carpeta dist)
      - name: Create deploy artifact (build.zip)
        run: |
          cd dist
          zip -r ../build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F2B6CAED77474548A9F66B6E279BBF32 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_731A38A575C143B0864AC079B7ABF410 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DE358A296A348C4BF7D6CA9B43F8A13 }}

      - name: Deploy (zip, clean)
        run: |
          RG=$(az webapp show -n gestionPasantias --query resourceGroup -o tsv)
          az webapp deploy \
            --resource-group "$RG" \
            --name gestionPasantias \
            --type zip \
            --src-path build.zip \
            --clean true
